name: ansible-lint
on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  lint:
    name: ansible-lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Set up Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          python -m pipenv install --dev --system

      - name: Install required collections
        run: ansible-galaxy collection install -r collections/requirements.yml

      - name: Run ansible-lint
        run: ansible-lint *.yml

  automerge:
    name: Auto-merge
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge pull requests from dependabot (patches only)
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_LOGIN: dependabot[bot]
          PRESET: DEPENDABOT_PATCH